### ISSUE TITLE
name error

### ISSUE THREAD

**Issue by MalikRumi** [idlesign/django-sitecats#10]
I'm having some difficulty with your app:

models.py
from sitecats.models import ModelWithCategory  # this was just a guess on my part
...
    class Entry(sitecats.models.ModelWithCategory):
NameError: name 'sitecats' is not defined

urls
    url(r'^sitecats/', include('sitecats.urls')),   

settings
INSTALLED_APPS = [
    'django.contrib.admin',
    ...
    'sitecats',
]

I used pip install and the app is in site packages inside a venv. What's wrong?

**Comment by idlesign** [comment]
You're misinterpreting import machinery.

Make you class definition either

```
from sitecats.models import ModelWithCategor
class Entry(ModelWithCategory):
```

or

```
import sitecats
class Entry(sitecats.models.ModelWithCategory):
```

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
