### ISSUE TITLE
Item with no categories doesn't display form

### ISSUE THREAD

**Issue by tomkcook** [idlesign/django-sitecats#2]
I'm running git HEAD.

In my views.py, I have this:

    class Gallery(ModelWithCategory):
        ...
        def get_context_data(self, **kwargs):
            context['gallery'].enable_category_lists_editor(self.request,
                        editor_init_kwargs = { 'allow_new': True },
                        lists_init_kwargs = { 'show_title': True, 'cat_html_class': 'label label-default'},
                        additional_parents_aliases = ['people', 'places'],
                        handler_init_kwargs = {})

and then in my template:

    {% load sitecats %}
    <div class="gallery-tags">
        {% sitecats_categories from gallery %}
    </div>

But the page doesn't show the form to add a tag to the object.  If I manually add a category to an object, using the django shell, then it displays both that tag and the form to add more.  But without manually adding the first tag, there is no way to add more.

How am I supposed to do this correctly?

**Comment by idlesign** [comment]
Personally I just define some basic categories to start with, but I'll see what could be done.
Thank you for the report.

**Comment by idlesign** [comment]
Docs updated. Let's stick with the described approach for now.
