### ISSUE TITLE
TypeError when calling enable_category_lists_editor

### ISSUE THREAD

**Issue by pritstift** [idlesign/django-sitecats#4]
I am trying to use sitecats with django 1.8 and python 3.4. Trying to enable category lists by calling the appropriate function, i get ```type object argument after ** must be a mapping, not NoneType```

Please find the traceback here: https://gist.github.com/fcb9fb536798c3c7e8f0.git

**Comment by pritstift** [comment]
Ok. I looked into the source and found out that passing ```handler_init_kwargs={}``` is sufficient. Is this behaviour wanted?

**Comment by idlesign** [comment]
Sorry for the delay. 

I'm unable to reach your code by that link, yet I suppose, you're talking about `enable_category_lists_editor()`. That's a bug, and it'll be fiexed in next release.

Thank you for the report.

**Comment by idlesign** [comment]
Seems to be fixed.
