### ISSUE TITLE
django-sitecats-helpers

### ISSUE THREAD

**Issue by bashu** [idlesign/django-sitecats#9]
Hey,

Thanks for `django-sitecats` app and here is my small contribution https://github.com/bashu/django-sitecats-helpers

Q: is it worth mentioning in docs?

**Comment by idlesign** [comment]
Hi, Basil,

That's interesting. Thank you.

Yes I certainly could mention your app in the docs, yet I'd like to propose you promoting it into `sitecats` itself. If you make a pull request I should merge it. You just put what you have in readme into docs, and we're almost ready to go.

A note: addressing categories by alias (as in  https://github.com/bashu/django-sitecats-helpers/blob/develop/sitecats_helpers/admin.py#L25) won't do in most cases, it's more reliable to use `id`.

**Comment by idlesign** [comment]
So what's you decision on incorporation? Would you like `helpers` to be merged into `sitecats`?

**Comment by bashu** [comment]
RemindMe! 2 days "merge helpers into sitecats"

**Comment by idlesign** [comment]
Ping.

**Comment by bashu** [comment]
@idlesign I'm still busy, but will be next thing in my TODO list, thank for your patience

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
